# -*- coding: utf-8 -*-
"""
/***************************************************************************
 vectorComparator
                                 A QGIS plugin
 Ta wtyczka porównuje dwie warstwy wektorowe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-15
        copyright            : (C) 2024 by Seweryn Piasecki
        email                : seweryn.piasecki@radom.lasy.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Seweryn Piasecki'
__date__ = '2024-03-15'
__copyright__ = '(C) 2024 by Seweryn Piasecki'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load vectorComparator class from file vectorComparator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vector_comparator import vectorComparatorPlugin
    return vectorComparatorPlugin()
